# Generated by Django 5.2.8 on 2025-12-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tenant_income_verification_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='background_check_files',
            field=models.JSONField(blank=True, default=list, help_text='List of uploaded background check file paths'),
        ),
    ]
