# Generated by Django 5.2.8 on 2025-12-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tenant_background_check_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('Applicant', 'Applicant'), ('Approved', 'Approved'), ('Active', 'Active'), ('Past', 'Past'), ('Eviction Pending', 'Eviction Pending'), ('Declined', 'Declined')], default='Applicant', max_length=50),
        ),
    ]
