# Generated by Django 5.2.8 on 2026-01-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_tenant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=2.0, help_text='Number of bathrooms', max_digits=3),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=2, help_text='Number of bedrooms'),
        ),
        migrations.AddField(
            model_name='property',
            name='square_footage',
            field=models.IntegerField(default=1000, help_text='Square footage'),
        ),
    ]
