# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_property_bathrooms_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_of_payment_files',
            field=models.JSONField(blank=True, default=list, help_text='List of uploaded proof of payment file paths (screenshots/receipts)'),
        ),
    ]
