# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_payment_proof_of_payment_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='furnishing_type',
            field=models.CharField(blank=True, help_text='Semi-furnished or Fully-furnished', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishings_breakdown',
            field=models.JSONField(blank=True, default=list, help_text='List of items available, e.g. ["Sofa", "Dining table", "Bed"]'),
        ),
    ]
