# Generated by Django 5.2.8 on 2026-03-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, help_text='Area/location for filtering (e.g. Avenue Q, Sherman St). If missing, can be derived from address.', max_length=120, null=True),
        ),
    ]
