# Generated by Django 5.2.8 on 2026-03-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_legaldocument_dropbox_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='signing_audit',
            field=models.JSONField(blank=True, help_text='Who signed, when, IP, etc.', null=True),
        ),
    ]
