# Generated by Django 5.2.8 on 2026-03-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_signing_audit'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Some environments may already have these columns (manual SQL or different migration history).
                # Make the migration idempotent for Postgres.
                migrations.RunSQL(
                    sql=(
                        """
                        ALTER TABLE api_property
                          ADD COLUMN IF NOT EXISTS area varchar(120) NULL;
                        ALTER TABLE api_property
                          ADD COLUMN IF NOT EXISTS status varchar(20) NOT NULL DEFAULT 'vacant';
                        """
                    ),
                    reverse_sql=(
                        """
                        ALTER TABLE api_property DROP COLUMN IF EXISTS status;
                        ALTER TABLE api_property DROP COLUMN IF EXISTS area;
                        """
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='property',
                    name='area',
                    field=models.CharField(
                        blank=True,
                        help_text='Area/location for filtering (e.g. Avenue Q, Sherman St). If missing, can be derived from address.',
                        max_length=120,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name='property',
                    name='status',
                    field=models.CharField(
                        choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')],
                        default='vacant',
                        help_text='Vacant = available to apply; Occupied = hide Apply button and show label',
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
