# Generated by Django 5.2.8 on 2026-06-16 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_operating_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legaldocument',
            name='dropbox_sign_signature_request_id',
        ),
        migrations.RemoveField(
            model_name='legaldocument',
            name='dropbox_sign_signing_url',
        ),
        migrations.AddField(
            model_name='operatingexpense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operatingexpense',
            name='visibility',
            field=models.CharField(choices=[('operating', 'Operating (visible to managers)'), ('admin_only', 'Admin only (financing / ownership)')], default='operating', help_text='Admin-only expenses (mortgage, depreciation) are hidden from property managers', max_length=20),
        ),
        migrations.AlterField(
            model_name='operatingexpense',
            name='category',
            field=models.CharField(choices=[('utilities', 'Utilities'), ('maintenance', 'Maintenance'), ('taxes', 'Taxes'), ('insurance', 'Insurance'), ('management', 'Management'), ('cleaning', 'Cleaning'), ('hoa', 'HOA Fees'), ('advertising', 'Advertising / Leasing'), ('legal', 'Legal & Professional'), ('supplies', 'Supplies & Materials'), ('transportation', 'Transportation'), ('bank_charges', 'Bank Charges'), ('mortgage_interest', 'Mortgage Interest'), ('mortgage_principal', 'Mortgage Principal'), ('depreciation', 'Depreciation'), ('other', 'Other')], default='utilities', max_length=50),
        ),
        migrations.CreateModel(
            name='PropertyFinancials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('closing_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('loan_term_years', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_mortgage_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('land_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('annual_depreciation_years', models.DecimalField(decimal_places=1, default=27.5, max_digits=5)),
                ('escrow_notes', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='api.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('properties', models.ManyToManyField(blank=True, related_name='managers', to='api.property')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Door 1, Unit A', max_length=100)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('vacant', 'Vacant'), ('coming_soon', 'Coming Soon')], default='vacant', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_units', to='api.property')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('property', 'label')},
            },
        ),
        migrations.AddField(
            model_name='operatingexpense',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_expenses', to='api.propertyunit'),
        ),
    ]
