# Generated by Django 5.2.8 on 2026-06-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_legaldocument_dropbox_sign_signature_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='short_stay_listing_area',
            field=models.CharField(blank=True, default='', help_text='Vague neighborhood label shown to guests (no street address)', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='short_stay_listing_description',
            field=models.TextField(blank=True, default='', help_text='Guest-facing marketing blurb for short-stay listings'),
        ),
        migrations.AddField(
            model_name='property',
            name='short_stay_listing_title',
            field=models.CharField(blank=True, default='', help_text='Guest-facing Airbnb-style title (hides real property name)', max_length=255),
        ),
    ]
