# Generated by Django 5.2.8 on 2026-06-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('property_manager', 'Property Manager')], default='tenant', max_length=30),
        ),
    ]
